name: Android Check CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execution permission to gradlew
      run: chmod +x ./gradlew

    - name: Build the Debug APK with Gradle
      run: ./gradlew build

    - name: Check the Debug APK
      run: ls app/build/outputs/apk/debug/app-debug.apk
