name: Android Build CI

on:
  push:
    branches: [ "main" ]
    tags: ['v*']

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execution permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: Write the encoded store key file from secrets
      env:
        STORE_KEY_FILE_BASE64: "${{ secrets.STORE_KEY_FILE_BASE64 }}"
      run: echo "$STORE_KEY_FILE_BASE64" > /tmp/skf64

    - name: Decode the store key file
      run: base64 --decode /tmp/skf64 > /tmp/skf.jks

    - name: Sign the Release APK
      env:
        STORE_PASSWORD: "${{ secrets.STORE_PASSWORD }}"
        STORE_KEY_PASSWORD: "${{ secrets.STORE_KEY_PASSWORD }}"
        STORE_KEY_FILE_PATH: /tmp/skf.jks
        STORE_KEY_ALIAS: "${{ secrets.STORE_KEY_ALIAS }}"
      run: |
        ./gradlew assembleRelease \
        -Pandroid.injected.signing.store.file="$STORE_KEY_FILE_PATH" \
        -Pandroid.injected.signing.store.password="$STORE_PASSWORD" \
        -Pandroid.injected.signing.key.alias="$STORE_KEY_ALIAS" \
        -Pandroid.injected.signing.key.password="$STORE_KEY_PASSWORD"

    - name: Delete the store key files
      run: rm /tmp/skf64 && rm /tmp/skf.jks

    - name: Check Debug APK
      run: ls app/build/outputs/apk/debug/app-debug.apk

    - name: Check Release APK
      run: ls app/build/outputs/apk/release/app-release.apk

      # Upload the APKs to the Releases if there is a git tag
      # Docs: https://github.com/softprops/action-gh-release
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          app/build/outputs/apk/debug/app-debug.apk
          app/build/outputs/apk/release/app-release.apk
